const items1 = [
    {
      title: "Lunchpad",
      id: "sb_launchpad",
      parent: true,
      childs: [
        {
          title: "MarketPlace",
          id: "sb_app-marketplace",
          img: "",
          url: "integration",
        },
        {
          title: "Mobile App",
          id: "sb_location-mobile-app",
          img: "",
          url: "mobile_app",
        },
        {
          title: "Docusign",
          id: "1670b203-aa0b-46d8-b4d6-d06f82390103",
          img: "",
          url: "custom-menu-link/1670b203-aa0b-46d8-b4d6-d06f82390103",
        },
      ],
    },
    {
      title: "My Business",
      id: "sb_dashboard",
      parent: true,
      childs: [
        {
          title: "Business PipeLine",
          id: "sb_opportunities",
          img: "",
          url: "list",
        },
        {
          title: "Property Search",
          id: "5f4e2642-7871-4206-96a6-a13e25a49c86",
          img: "",
          url: "propertySearch",
        },
        {
          title: "Contacts",
          id: "sb_contacts",
          img: "",
          url: "contacts/smart_list/All",
        },
        {
          title: "Message Center",
          id: "sb_conversations",
          img: "",
          url: "conversations",
        },
      ],
    },
    {
      title: "Calendars",
      id: "sb_calendars",
      parent: true,
      childs: [
        {
          title: "Calendar Blocking",
          id: "f3fd01b6-24e0-44e7-8478-696672f9dfe7",
          img: "",
          url: "custom-menu-link/f3fd01b6-24e0-44e7-8478-696672f9dfe7",
        },
      ],
    },
    {
      title: "Database Marketing",
      id: "sb_email-marketing",
      parent: true,
      childs: [
        {
          title: "Automation",
          id: "sb_automation",
          img: "",
          url: "automation/workflows",
        },
        {
          title: "Website & Forms",
          id: "sb_sites",
          img: "",
          url: "funnels-websites/funnels",
        },
        {
          title: "Review Management",
          id: "sb_reputation",
          img: "",
          url: "reputation/overview",
        },
        {
          title: "Thanks.io",
          id: "24a2f8c7-7a36-442e-9d29-d0fe7533b941",
          img: "",
          url: "custom-menu-link/24a2f8c7-7a36-442e-9d29-d0fe7533b941",
        },
        {
          title: "Online Ad Metrics",
          id: "sb_reporting",
          img: "",
          url: "reporting/reports",
        },
        {
          title: "Media Storage",
          id: "sb_app-media",
          img: "",
          url: "media-storage",
        },
        {
          title: "Training Center",
          id: "sb_memberships",
          img: "",
          url: "client-portal/dashboard",
        },
      ],
    },
    {
      title: "Settings",
      id: "sb_settings",
      parent: true,
      childs: [
        {
          parent: true,
          title: "My Business",
          id: "#",
          img: "",
          childs: [
            {
              title: "Billing",
              id: "sb_saas-billing",
              img: "",
              url: "settings/company-billing/billing",
            },
            {
              title: "My Staff",
              id: "sb_my-staff",
              img: "",
              url: "settings/staff/team",
            },
            {
              title: "Opportunities & Pipelines",
              id: "sb_Opportunities-Pipelines",
              img: "",
              url: "crm-settings",
            },
          ],
        },
        {
          parent: true,
          title: "Business Services",
          id: "#",
          img: "",
          childs: [
            {
              title: "Automation",
              id: "sb_automation-setting",
              img: "",
              url: "settings/automation",
            },
            {
              title: "Calendars",
              id: "sb_calendars-setting",
              img: "",
              url: "settings/calendars/",
            },
            {
              title: "Conversion AI",
              id: "sb_conversation_ai_settings_v2",
              img: "",
              url: "settings/conversation-ai-v2/",
            },
            {
              title: "Voice AI Agents",
              id: "sb_ai_agent_settings",
              img: "",
              url: "settings/ai-agents/",
            },
            {
              title: "Email Services",
              id: "sb_location-email-services",
              img: "",
              url: "settings/smtp_service",
            },
            {
              title: "Phone Numbers",
              id: "sb_phone-number",
              img: "",
              url: "settings/phone_number",
            },
            {
              title: "Whats App",
              id: "sb_whatsapp",
              img: "",
              url: "settings/whatsapp",
            },
          ],
        },
        {
          parent: true,
          title: "Other Settings",
          id: "#",
          img: "",
          childs: [
            {
              title: "Objects ",
              id: "sb_objects",
              img: "",
              url: "settings/objects/",
            },
            {
              title: "Custom Fields",
              id: "sb_custom-fields-settings",
              img: "",
              url: "settings/fields",
            },
            {
              title: "Custom Values",
              id: "sb_custom-values",
              img: "",
              url: "settings/custom_values",
            },
            {
              title: "Manage Scoring",
              id: "sb_manage-scoring",
              img: "",
              url: "settings/scoring",
            },
            {
              title: "Domains",
              id: "sb_domains",
              img: "",
              url: "settings/domain",
            },
            {
              title: "URL Redirects",
              id: "sb_url-redirects",
              img: "",
              url: "settings/redirect",
            },
            {
              title: "Integrations",
              id: "sb_integrations",
              img: "",
              url: "settings/integrations/list",
            },
            {
              title: "Private Integrations",
              id: "sb_private_integration",
              img: "",
              url: "settings/private-integrations/",
            },
            {
              title: "Conversation Providers",
              id: "sb_conversations_providers",
              img: "",
              url: "settings/conversation_providers",
            },
            { title: "Tags", id: "sb_tags", img: "", url: "settings/tags" },
            { title: "Labs", id: "sb_labs", img: "", url: "settings/labs" },
            {
              title: "Audit Logs",
              id: "sb_audit-logs-location",
              img: "",
              url: "settings/audit/logs",
            },
            {
              title: "Brand Boards",
              id: "sb_brand-boards",
              img: "",
              url: "marketing/brand-boards",
            },
            {
              title: "Companies",
              id: "sb_business-settings-v2",
              img: "",
              url: "settings/objects/6789681baae233321f75964f/details",
            },
          ],
        },
      ],
    },
  ];