let Item = {
    "data": {
        "inventoryCollection": {
            "pageInfo": {
                "startCursor": "eyJpZCI6MzI3MiwibmFtZSI6IjIwMDMgQ2hldnJvbGV0IFNpbHZlcmFkbyAxNTAwICJ9",
                "endCursor": "eyJpZCI6MzI0NywibmFtZSI6IjIwMDggTWF6ZGEgTWF6ZGE1IFNwb3J0In0=",
                "hasNextPage": true,
                "hasPreviousPage": false
            },
            "edges": [
                {
                    "node": {
                        "id": "3272",
                        "uuid": "rec19g639maocwhxn",
                        "startedAt": null,
                        "year": 2003,
                        "make": "Chevrolet",
                        "model": "Silverado 1500",
                        "bodyStyle": "Truck",
                        "trim": null,
                        "miles": 146595,
                        "engineSize": null,
                        "engineCylinders": null,
                        "transmission": null,
                        "drivetrain": null,
                        "fuelType": null,
                        "exteriorColor": null,
                        "interiorColor": null,
                        "interiorMaterial": null,
                        "listedPrice": 0,
                        "vehicleCost": 2700,
                        "vdpUrl": "https:\/\/www.premiummotors.com\/\/viewInventory\/925741\/",
                        "photosUrls": null,
                        "notes": null,
                        "status": "INACTIVE",
                        "disabled": null,
                        "featuredPhoto": null,
                        "description": null,
                        "subHeader": null,
                        "name": "2003 Chevrolet Silverado 1500 ",
                        "inventoryVinDecodeMessage": null,
                        "stateBodyCode": null,
                        "ignoreFeedSync": null,
                        "dealershipSubAccountId": "geAOl3NEW1iIKIWheJcj",
                        "vehicleOptions": null,
                        "descriptionGptSummary": null,
                        "descriptionAiCharactersCount": null,
                        "descriptionAiHighlights": null,
                        "descriptionGenerationgResponse": null,
                        "buyersGuide": null,
                        "dealershipAddress": "14778 E Broad st, Reynoldsburg, Ohio, 43068, United States",
                        "dealershipPhone": "+1 6143777169",
                        "dealershipEmail": "saso@premiummotors.com",
                        "vinDecodeCall": null,
                        "fuelEconomy": null,
                        "mpgCity": null,
                        "mpgHighway": null,
                        "mpgCombined": null,
                        "vin2": null,
                        "powertrainFeatures": null,
                        "safetyFeatures": null,
                        "interiorFeatures": null,
                        "exteriorFeatures": null,
                        "condition": null,
                        "exteriorColorFeed": null,
                        "exteriorColorWeb": null,
                        "interiorColorFeed": null,
                        "interiorColorWeb": null,
                        "interiorMaterialFeed": null,
                        "interiorMaterialWeb": null,
                        "cleanTradeValue": null,
                        "retailValue": null,
                        "vin": "2GCEC19V231121431",
                        "stock": "11941",
                        "feedFileName": null,
                        "dealershipName": "Premium Motors LLC",
                        "dealershipLogoUrl": "https:\/\/storage.googleapis.com\/msgsndr\/geAOl3NEW1iIKIWheJcj\/media\/65ea19b65f0c0f51d112d380.png",
                        "dealershipHistoryReport": "CARFAX",
                        "bodyType": null
                    }
                },
                {
                    "node": {
                        "id": "3261",
                        "uuid": "rec19g615maocw7o8",
                        "startedAt": null,
                        "year": 2005,
                        "make": "BMW",
                        "model": "X5",
                        "bodyStyle": "SUV",
                        "trim": "4.4i",
                        "miles": 123000,
                        "engineSize": "4.4",
                        "engineCylinders": "8",
                        "transmission": "6-Speed Shiftable Automatic",
                        "drivetrain": "awd",
                        "fuelType": "gas",
                        "exteriorColor": null,
                        "interiorColor": null,
                        "interiorMaterial": null,
                        "listedPrice": 0,
                        "vehicleCost": 900,
                        "vdpUrl": "https:\/\/www.premiummotors.com\/\/viewInventory\/845508\/",
                        "photosUrls": null,
                        "notes": null,
                        "status": "INACTIVE",
                        "disabled": null,
                        "featuredPhoto": null,
                        "description": null,
                        "subHeader": null,
                        "name": "2005 BMW X5 4.4i",
                        "inventoryVinDecodeMessage": null,
                        "stateBodyCode": null,
                        "ignoreFeedSync": null,
                        "dealershipSubAccountId": "geAOl3NEW1iIKIWheJcj",
                        "vehicleOptions": "Leather Seats,Roof rack crossbars: black,Driver seat power adjustments: ,Front headrests: adjustable  2,Front seat type: bucket,Passenger seat power adjustments: ,Rear seat folding: split,Rear seat type: bench,Upholstery: leather,ABS: 4-wheel,Front fog lights: ,Headlights: HID\/Xenon,Parking sensors: front  rear,Front airbags: dual,Side airbags: front,Side curtain airbags: front  rear,Side mirror adjustments: power,Side mirrors: heated,Front wipers: intermittent  rain sensing,Power windows: ,Rear wiper: intermittent,Window defogger: rear,Anti-theft system: alarm,Power door locks: ,Limited slip differential: center,In-Dash CD: single disc,Radio: AM\/FM,Wheel diameter: 18 inch,Wheels: alloy,Clock: ,Gauge: tachometer,Trip odometer: ,Air filtration: active charcoal,Front air conditioning: automatic climate control,Front air conditioning zones: dual,Rear air conditioning: independently controlled,Rear air conditioning zones: dual,Center console trim: leather  wood,Dash trim: wood,Door trim: leather  wood,Shift knob trim: leather  wood,Steering wheel trim: leather,Rear spoiler: ,Center console: front console with storage,Cruise control: ,Easy entry: power driver seat,Memorized settings: driver seat,Multi-function remote: keyless entry,Overhead console: front,Power steering: ,Steering wheel: tilt and telescopic,Steering wheel mounted controls: audio,Universal remote transmitter: garage door opener,Off-road driving assist: hill descent,Stability control: ,Traction control: ",
                        "descriptionGptSummary": null,
                        "descriptionAiCharactersCount": null,
                        "descriptionAiHighlights": null,
                        "descriptionGenerationgResponse": null,
                        "buyersGuide": null,
                        "dealershipAddress": "14778 E Broad st, Reynoldsburg, Ohio, 43068, United States",
                        "dealershipPhone": "+1 6143777169",
                        "dealershipEmail": "saso@premiummotors.com",
                        "vinDecodeCall": null,
                        "fuelEconomy": null,
                        "mpgCity": "14",
                        "mpgHighway": "20",
                        "mpgCombined": null,
                        "vin2": null,
                        "powertrainFeatures": null,
                        "safetyFeatures": null,
                        "interiorFeatures": null,
                        "exteriorFeatures": null,
                        "condition": null,
                        "exteriorColorFeed": null,
                        "exteriorColorWeb": null,
                        "interiorColorFeed": null,
                        "interiorColorWeb": null,
                        "interiorMaterialFeed": null,
                        "interiorMaterialWeb": null,
                        "cleanTradeValue": null,
                        "retailValue": null,
                        "vin": "5UXFB53525LV13618",
                        "stock": "11843",
                        "feedFileName": null,
                        "dealershipName": "Premium Motors LLC",
                        "dealershipLogoUrl": "https:\/\/storage.googleapis.com\/msgsndr\/geAOl3NEW1iIKIWheJcj\/media\/65ea19b65f0c0f51d112d380.png",
                        "dealershipHistoryReport": "CARFAX",
                        "bodyType": null
                    }
                },
                {
                    "node": {
                        "id": "3289",
                        "uuid": "rec19g616maocwrx9",
                        "startedAt": null,
                        "year": 2007,
                        "make": "Nissan",
                        "model": "Altima",
                        "bodyStyle": "Car",
                        "trim": "2.5",
                        "miles": 244992,
                        "engineSize": "2.5",
                        "engineCylinders": "4",
                        "transmission": "6-Speed Manual",
                        "drivetrain": "fwd",
                        "fuelType": "gas",
                        "exteriorColor": null,
                        "interiorColor": null,
                        "interiorMaterial": null,
                        "listedPrice": 0,
                        "vehicleCost": 800,
                        "vdpUrl": "https:\/\/www.premiummotors.com\/\/viewInventory\/917751\/",
                        "photosUrls": null,
                        "notes": null,
                        "status": "INACTIVE",
                        "disabled": null,
                        "featuredPhoto": null,
                        "description": null,
                        "subHeader": null,
                        "name": "2007 Nissan Altima 2.5",
                        "inventoryVinDecodeMessage": null,
                        "stateBodyCode": null,
                        "ignoreFeedSync": null,
                        "dealershipSubAccountId": "geAOl3NEW1iIKIWheJcj",
                        "vehicleOptions": "Driver seat manual adjustments: height  lumbar, 6,Front headrests: adjustable  2,Front seat type: bucket,Passenger seat manual adjustments: 4,Rear headrests: integrated  2,Rear seat folding: split,Rear seat type: bench,Upholstery: cloth,Front brake diameter: 11.7,Front brake type: ventilated disc,Front brake width: 1.0,Rear brake diameter: 11.5,Rear brake type: disc,Rear brake width: 0.4,Active head restraints: dual front,Child safety door locks: ,Child seat anchors: ,Emergency interior trunk release: ,Airbag deactivation: occupant sensing passenger,Front airbags: dual,Side airbags: front,Side curtain airbags: front  rear,Side mirror adjustments: power,Front wipers: intermittent,Power windows: ,Window defogger: rear,Anti-theft system: alarm  vehicle immobilizer,Power door locks: ,Rear seatbelts: center 3-point,Seatbelt force limiters: front,Seatbelt pretensioners: front,Front shock type: gas,Front spring type: coil,Front stabilizer bar: ,Front struts: MacPherson,Front suspension classification: independent,Front suspension type: lower control arms,Rear shock type: gas,Rear spring type: coil,Rear stabilizer bar: ,Rear suspension classification: independent,Rear suspension type: multi-link,Antenna type: element,Spare tire mount location: inside,Spare tire size: temporary,Spare wheel type: steel,Tire Pressure Monitoring System: ,Tire prefix: P,Tire type: all season,Wheel covers: full,Wheels: steel,Gauge: tachometer,Warnings and reminders: low fuel level,Armrests: rear center folding with storage,Cargo area light: ,Center console: front console with storage,Cruise control: ,Cupholders: front  rear,Multi-function remote: proximity entry system  trunk release,One-touch windows: 1,Overhead console: front,Power outlet(s): 12V front,Power steering: variable\/speed-proportional,Push-button start: ,Reading lights: front  rear,Steering wheel: tilt and telescopic,Steering wheel mounted controls: cruise control,Storage: door pockets,Vanity mirrors: dual",
                        "descriptionGptSummary": null,
                        "descriptionAiCharactersCount": null,
                        "descriptionAiHighlights": null,
                        "descriptionGenerationgResponse": null,
                        "buyersGuide": null,
                        "dealershipAddress": "14778 E Broad st, Reynoldsburg, Ohio, 43068, United States",
                        "dealershipPhone": "+1 6143777169",
                        "dealershipEmail": "saso@premiummotors.com",
                        "vinDecodeCall": null,
                        "fuelEconomy": null,
                        "mpgCity": "23",
                        "mpgHighway": "32",
                        "mpgCombined": null,
                        "vin2": null,
                        "powertrainFeatures": null,
                        "safetyFeatures": null,
                        "interiorFeatures": null,
                        "exteriorFeatures": null,
                        "condition": null,
                        "exteriorColorFeed": null,
                        "exteriorColorWeb": null,
                        "interiorColorFeed": null,
                        "interiorColorWeb": null,
                        "interiorMaterialFeed": null,
                        "interiorMaterialWeb": null,
                        "cleanTradeValue": null,
                        "retailValue": null,
                        "vin": "1N4AL21E57C164358",
                        "stock": "11920",
                        "feedFileName": null,
                        "dealershipName": "Premium Motors LLC",
                        "dealershipLogoUrl": "https:\/\/storage.googleapis.com\/msgsndr\/geAOl3NEW1iIKIWheJcj\/media\/65ea19b65f0c0f51d112d380.png",
                        "dealershipHistoryReport": "CARFAX",
                        "bodyType": null
                    }
                },
                {
                    "node": {
                        "id": "3246",
                        "uuid": "rec19g616maocvxup",
                        "startedAt": null,
                        "year": 2008,
                        "make": "Mazda",
                        "model": "Mazda5",
                        "bodyStyle": "Van",
                        "trim": "Sport",
                        "miles": 156243,
                        "engineSize": "2.3",
                        "engineCylinders": "4",
                        "transmission": "5-Speed Manual",
                        "drivetrain": "fwd",
                        "fuelType": "gas",
                        "exteriorColor": null,
                        "interiorColor": null,
                        "interiorMaterial": null,
                        "listedPrice": 0,
                        "vehicleCost": 800,
                        "vdpUrl": "https:\/\/www.premiummotors.com\/\/viewInventory\/909312\/",
                        "photosUrls": null,
                        "notes": null,
                        "status": "INACTIVE",
                        "disabled": null,
                        "featuredPhoto": null,
                        "description": null,
                        "subHeader": null,
                        "name": "2008 Mazda Mazda5 Sport",
                        "inventoryVinDecodeMessage": null,
                        "stateBodyCode": null,
                        "ignoreFeedSync": null,
                        "dealershipSubAccountId": "geAOl3NEW1iIKIWheJcj",
                        "vehicleOptions": "Rear door type: liftgate,Side door type: passenger-side manual sliding,Driver seat manual adjustments: height  lumbar, 6,Front headrests: adjustable  2,Front seat type: bucket,Passenger seat manual adjustments: 4,Rear headrests: adjustable  2,Rear seat folding: one-piece,Rear seat type: captains chairs,Third row headrests: 2,Third row seat folding: split,Third row seat type: 50-50 split bench,Upholstery: cloth,ABS: 4-wheel,Braking assist: ,Electronic brakeforce distribution: ,Front brake diameter: 11.8,Front brake type: ventilated disc,Front brake width: 1.0,Rear brake diameter: 11.9,Rear brake type: disc,Rear brake width: 0.4,Child safety door locks: ,Child seat anchors: ,Airbag deactivation: occupant sensing passenger,Front airbags: dual,Side airbags: front,Side curtain airbags: front  rear, third row,Side mirror adjustments: power,Front wipers: variable intermittent,Power windows: ,Rear wiper: intermittent,Window defogger: rear,2-stage unlocking doors: ,Anti-theft system: engine immobilizer,Power door locks: ,Seatbelt force limiters: front,Seatbelt pretensioners: front,Axle ratio: 4.39,Front shock type: gas,Front spring type: coil,Front stabilizer bar: ,Front struts: MacPherson,Front suspension classification: independent,Front suspension type: lower control arms,Rear shock type: gas,Rear spring type: coil,Rear stabilizer bar: ,Rear suspension classification: independent,Rear suspension type: multi-link,Antenna type: mast,Auxiliary audio input: MP3,In-Dash CD: single disc,Radio: AM\/FM,Total speakers: 6,Spare tire mount location: inside,Spare tire size: temporary,Spare wheel type: steel,Tire Pressure Monitoring System: ,Tire prefix: P,Tire type: all season,Clock: ,Electroluminescent instrumentation: ,External temperature display: ,Gauge: tachometer,Warnings and reminders: low fuel level  tire fill alert,Air filtration: ,Front air conditioning: automatic climate control,Front air conditioning zones: single,Rear heat: independently controlled,Floor mat material: carpet,Floor mats: front  rear,Cargo area light: ,Center console: front console with storage,Cruise control: ,Cupholders: front  rear, third row,Multi-function remote: keyless entry  trunk release,One-touch windows: 1,Power outlet(s): 12V cargo area  12V front,Power steering: variable\/speed-proportional,Reading lights: front,Steering wheel: tilt and telescopic,Steering wheel mounted controls: audio  cruise control,Storage: door pockets  front seatback,Vanity mirrors: dual",
                        "descriptionGptSummary": null,
                        "descriptionAiCharactersCount": null,
                        "descriptionAiHighlights": null,
                        "descriptionGenerationgResponse": null,
                        "buyersGuide": null,
                        "dealershipAddress": "14778 E Broad st, Reynoldsburg, Ohio, 43068, United States",
                        "dealershipPhone": "+1 6143777169",
                        "dealershipEmail": "saso@premiummotors.com",
                        "vinDecodeCall": null,
                        "fuelEconomy": null,
                        "mpgCity": "22",
                        "mpgHighway": "28",
                        "mpgCombined": null,
                        "vin2": null,
                        "powertrainFeatures": null,
                        "safetyFeatures": null,
                        "interiorFeatures": null,
                        "exteriorFeatures": null,
                        "condition": null,
                        "exteriorColorFeed": null,
                        "exteriorColorWeb": null,
                        "interiorColorFeed": null,
                        "interiorColorWeb": null,
                        "interiorMaterialFeed": null,
                        "interiorMaterialWeb": null,
                        "cleanTradeValue": null,
                        "retailValue": null,
                        "vin": "JM1CR29L680302870",
                        "stock": "11905",
                        "feedFileName": null,
                        "dealershipName": "Premium Motors LLC",
                        "dealershipLogoUrl": "https:\/\/storage.googleapis.com\/msgsndr\/geAOl3NEW1iIKIWheJcj\/media\/65ea19b65f0c0f51d112d380.png",
                        "dealershipHistoryReport": "CARFAX",
                        "bodyType": null
                    }
                },
                {
                    "node": {
                        "id": "3247",
                        "uuid": "rec19g617maocvy32",
                        "startedAt": null,
                        "year": 2008,
                        "make": "Mazda",
                        "model": "Mazda5",
                        "bodyStyle": "Van",
                        "trim": "Sport",
                        "miles": 156243,
                        "engineSize": "2.3",
                        "engineCylinders": "4",
                        "transmission": "5-Speed Manual",
                        "drivetrain": "fwd",
                        "fuelType": "gas",
                        "exteriorColor": null,
                        "interiorColor": null,
                        "interiorMaterial": null,
                        "listedPrice": 0,
                        "vehicleCost": 400,
                        "vdpUrl": "https:\/\/www.premiummotors.com\/\/viewInventory\/909310\/",
                        "photosUrls": null,
                        "notes": null,
                        "status": "INACTIVE",
                        "disabled": null,
                        "featuredPhoto": null,
                        "description": null,
                        "subHeader": null,
                        "name": "2008 Mazda Mazda5 Sport",
                        "inventoryVinDecodeMessage": null,
                        "stateBodyCode": null,
                        "ignoreFeedSync": null,
                        "dealershipSubAccountId": "geAOl3NEW1iIKIWheJcj",
                        "vehicleOptions": "Rear door type: liftgate,Side door type: passenger-side manual sliding,Driver seat manual adjustments: height  lumbar, 6,Front headrests: adjustable  2,Front seat type: bucket,Passenger seat manual adjustments: 4,Rear headrests: adjustable  2,Rear seat folding: one-piece,Rear seat type: captains chairs,Third row headrests: 2,Third row seat folding: split,Third row seat type: 50-50 split bench,Upholstery: cloth,ABS: 4-wheel,Braking assist: ,Electronic brakeforce distribution: ,Front brake diameter: 11.8,Front brake type: ventilated disc,Front brake width: 1.0,Rear brake diameter: 11.9,Rear brake type: disc,Rear brake width: 0.4,Child safety door locks: ,Child seat anchors: ,Airbag deactivation: occupant sensing passenger,Front airbags: dual,Side airbags: front,Side curtain airbags: front  rear, third row,Side mirror adjustments: power,Front wipers: variable intermittent,Power windows: ,Rear wiper: intermittent,Window defogger: rear,2-stage unlocking doors: ,Anti-theft system: engine immobilizer,Power door locks: ,Seatbelt force limiters: front,Seatbelt pretensioners: front,Axle ratio: 4.39,Front shock type: gas,Front spring type: coil,Front stabilizer bar: ,Front struts: MacPherson,Front suspension classification: independent,Front suspension type: lower control arms,Rear shock type: gas,Rear spring type: coil,Rear stabilizer bar: ,Rear suspension classification: independent,Rear suspension type: multi-link,Antenna type: mast,Auxiliary audio input: MP3,In-Dash CD: single disc,Radio: AM\/FM,Total speakers: 6,Spare tire mount location: inside,Spare tire size: temporary,Spare wheel type: steel,Tire Pressure Monitoring System: ,Tire prefix: P,Tire type: all season,Clock: ,Electroluminescent instrumentation: ,External temperature display: ,Gauge: tachometer,Warnings and reminders: low fuel level  tire fill alert,Air filtration: ,Front air conditioning: automatic climate control,Front air conditioning zones: single,Rear heat: independently controlled,Floor mat material: carpet,Floor mats: front  rear,Cargo area light: ,Center console: front console with storage,Cruise control: ,Cupholders: front  rear, third row,Multi-function remote: keyless entry  trunk release,One-touch windows: 1,Power outlet(s): 12V cargo area  12V front,Power steering: variable\/speed-proportional,Reading lights: front,Steering wheel: tilt and telescopic,Steering wheel mounted controls: audio  cruise control,Storage: door pockets  front seatback,Vanity mirrors: dual",
                        "descriptionGptSummary": null,
                        "descriptionAiCharactersCount": null,
                        "descriptionAiHighlights": null,
                        "descriptionGenerationgResponse": null,
                        "buyersGuide": null,
                        "dealershipAddress": "14778 E Broad st, Reynoldsburg, Ohio, 43068, United States",
                        "dealershipPhone": "+1 6143777169",
                        "dealershipEmail": "saso@premiummotors.com",
                        "vinDecodeCall": null,
                        "fuelEconomy": null,
                        "mpgCity": "22",
                        "mpgHighway": "28",
                        "mpgCombined": null,
                        "vin2": null,
                        "powertrainFeatures": null,
                        "safetyFeatures": null,
                        "interiorFeatures": null,
                        "exteriorFeatures": null,
                        "condition": null,
                        "exteriorColorFeed": null,
                        "exteriorColorWeb": null,
                        "interiorColorFeed": null,
                        "interiorColorWeb": null,
                        "interiorMaterialFeed": null,
                        "interiorMaterialWeb": null,
                        "cleanTradeValue": null,
                        "retailValue": null,
                        "vin": "JM1CR29L680302870",
                        "stock": "11904",
                        "feedFileName": null,
                        "dealershipName": "Premium Motors LLC",
                        "dealershipLogoUrl": "https:\/\/storage.googleapis.com\/msgsndr\/geAOl3NEW1iIKIWheJcj\/media\/65ea19b65f0c0f51d112d380.png",
                        "dealershipHistoryReport": "CARFAX",
                        "bodyType": null
                    }
                }
            ]
        }
    },
    "extensions": {
        "requestId": "19g616mar51xz7"
    }
}